language: python
python: 3.4
os: linux
compiler: gcc
addons:
    apt:
        packages:
            - libboost-test-dev
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create --yes -n test python=3.6
    - source $HOME/miniconda/bin/activate test
    - conda install --yes gsl numpy scipy h5py
    - git submodule update --init --recursive
    - python3 --version
install:
    - pip install runtests
    - python3 setup.py install
script:
    - python3 do_the_tests.py
    - make test

deploy:
    - provider: pypi
      distributions: sdist
      user: "simeonbird"
      password:
        secure: "RvJFN0PEOWv+RyeDNA1/s4pMUluhpk+ZoznRjDj6N0Bb9tc66JAOL8I7c/gmn9nAUd9gKQtVnxPsWLkCjcVgvRY9hVhoHiqHsoPCm0F6H16CnABJGqEzAd6kZZQg6Qcy5rhnRAXuw7YkDuX5MR4uHivli4UE+gvJGwVSYkPduVcoXG4V3dzV0IlvGx5UZ87xzPilSdrlsATjvtOxk93/3IL6mIQkBu26PtdLBTedp4V6vw8yl/tZ6O9MUqCuZALUSN2SLygf347jkDoOmjHRkJMtFNBiQ9rGHiA4ljtEw7ye8bCI4j/CEyjDVSIJf9KL/OUURHicE2F4GGpzaCITAjb3kDWxXYlOfygnDwWG08iGAjDOlqVlhiyCotq2X2+lH3iIYv5yqcB9SZpVTuypUfXsIG40TqGDvZv1GMvvAi8Yw/2QSjk3Z4FFKGy86ybv9a+bWXMFk0vqQNd8WMEQ6dSk6fCM9bJrVKF4lbFf7yKrpnrLrubv509VKGYbD1BfrD6KPNb1nzFcjJzHYYLvmTHVQj+Y32kKjS9lh+u4UUWaXOriN3RlQhKVRZE2xT/vF0Ebmr+TUb/RzfpxYil22Eaakle8hUXl0stQe7aRkvLXauXpOXAtVXK49KlhMj4MieoJk4e0CkumpCqRqiWypNLWVZV0m3YCdcbEHIbBl2s="
      on:
          tags: true
          condition: ${TRAVIS_JOB_NUMBER##*.} == 1
